name: driver
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3
  dotted_dashed_line: ^0.0.3
  font_awesome_flutter: ^10.7.0
  flutter_faq: ^1.0.1+1
  google_maps_flutter: ^2.9.0
  toggle_switch: ^2.3.0
  cached_network_image: ^3.4.0
  dio: ^5.4.0
  flutter_offline: ^2.1.0
  image_picker: ^1.1.2
  animate_do: ^3.3.4
  easy_localization: ^3.0.3
  shared_preferences: ^2.2.0
  intl: ^0.19.0
  flutter_widget_from_html: ^0.15.1
  flutter_screenutil: ^5.7.0
  logger: ^2.4.0
  html: ^0.15.4
  get_it: ^7.7.0
  pin_code_fields: ^8.0.1
  fluttertoast: ^8.2.6
  dotted_border: ^2.0.0
  rate: ^0.0.2
  firebase_core: ^3.2.0
  awesome_notifications: ^0.9.3+1
  firebase_messaging: ^15.1.0
  circular_countdown_timer: ^0.2.3
  easy_stepper: ^0.8.5+1
  enhance_stepper: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - assets/tajwal/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: tajwal
      fonts:
        - asset: assets/tajwal/Tajawal-Black.ttf
          weight: 900
        - asset: assets/tajwal/Tajawal-Bold.ttf
          weight: 800
        - asset: assets/tajwal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/tajwal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/tajwal/Tajawal-Regular.ttf
          weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
